version: "3.7"

services:
  nginx:
    container_name: ${DOCKER_APP_NAME}_ngnix
    depends_on:
      - php
    networks:
      - app

  php:
    container_name: ${DOCKER_APP_NAME}_php
    depends_on:
      - mysql
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  mysqldata:
    driver: local