version: "3.7"

services:
  nginx:
    container_name: ${DOCKER_APP_NAME}_ngnix
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - "./app/public/:/usr/src/app"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "${NGINX_PORT}:80"
    environment:
      - VIRTUAL_PORT=${NGINX_PORT}
      - VIRTUAL_PROTO=http
      - SSL_POLICY=Mozilla-Modern
    depends_on:
      - php
    networks:
      - app

  php:
    container_name: ${DOCKER_APP_NAME}_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - "./app:/usr/src/app"
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  mysqldata:
    driver: local